org.gradle.jvmargs=-Xmx2G -Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2,TLSv1.3 
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
loader_version=0.17.2

# Mod Properties
maven_group=net.shiroha233.roadweaverpg

# Dependencies
fabric_version=0.92.2+1.20.1
forge_version=47.3.0
dynamictrees_version=1.4.8

# Touhou Little Maid
touhou_little_maid_version=1.4.6-forge+mc1.20.1
touhou_little_maid_fabric_version=0.5.1-forge1.4.6
forge_config_api_port_version=v8.0.3-1.20.1-Fabric
cardinal_components_version=5.2.3
reach_entity_attributes_version=2.4.0

# Kaleidoscope Cookery (森罗物语)
kaleidoscope_cookery_fabric_version=1.0.1-fabric+mc1.20.1
kaleidoscope_cookery_forge_version=1.1.2-forge+mc1.20.1